(function(q,n){var b={version:"0.0.1",base:function(){}};b.base.extend=function(a,e){var d=b.base.prototype.extend;b.base._prototyping=!0;var c=new this;d.call(c,a);c.base=function(){};delete b.base._prototyping;var f=c.constructor,g=c.constructor=function(){if(!b.base._prototyping)if(this._constructing||this.constructor==g)this._constructing=!0,f.apply(this,arguments),delete this._constructing;else if(arguments[0]!=null)return(arguments[0].extend||d).call(arguments[0],c)};g.ancestor=this;g.extend=
this.extend;g.forEach=this.forEach;g.implement=this.implement;g.prototype=c;g.toString=this.toString;g.valueOf=function(a){return a=="object"?g:f.valueOf()};d.call(g,e);typeof g.init=="function"&&g.init();return g};b.base.prototype={extend:function(a,e){if(arguments.length>1){var d=this[a];if(d&&typeof e=="function"&&(!d.valueOf||d.valueOf()!=e.valueOf())&&/\bbase\b/.test(e)){var c=e.valueOf(),e=function(){var a=this.base||Base.prototype.base;this.base=d;var b=c.apply(this,arguments);this.base=a;
return b};e.valueOf=function(a){return a=="object"?e:c};e.toString=Base.toString}this[a]=e}else if(a){var f=b.base.prototype.extend;!b.base._prototyping&&typeof this!="function"&&(f=this.extend||f);for(var g={toSource:null},h=["constructor","toString","valueOf"],l=b.base._prototyping?0:1;k=h[l++];)a[k]!=g[k]&&f.call(this,k,a[k]);for(var k in a)g[k]||f.call(this,k,a[k])}return this}};b.base=b.base.extend({constructor:function(a){this.extend(a)}},{ancestor:Object,forEach:function(a,b,d){for(var c in a)this.prototype[c]===
n&&b.call(d,a[c],c,a)},implement:function(){for(var a=0;a<arguments.length;a++)if(typeof arguments[a]=="function")arguments[a](this.prototype);else this.prototype.extend(arguments[a]);return this},toString:function(){return String(this.valueOf())}});Number.prototype.times=function(a,b){for(var d=this.valueOf(),c=0;c<d;c++)a.call(b||this,c)};Array.prototype.each=function(a,b){for(var d=this.length,c=!!this.__sequence,f=c?this.__sequence.length:0,g=0;g<d;g++)g in this&&a.apply(b||this,c?[this.__sequence[g%
f],this[g],g,this]:[this[g],g,this])};Array.prototype.sequence=function(){this.__sequence=Array.prototype.slice.call(arguments);return this};(function(a){function b(a,r){for(var d=a.length;d--;)if(a[d]===r)return d;return-1}function d(a,b,d){var e,c,l,f;d===n&&(d=b,b="all");a=a.replace(/\s/g,"");e=a.split(",");e[e.length-1]==""&&(e[e.length-2]+=",");for(l=0;l<e.length;l++){c=[];a=e[l].split("+");if(a.length>1){c=a.slice(0,a.length-1);for(f=0;f<c.length;f++)c[f]=k[c[f]];a=[a[a.length-1]]}a=a[0];a=
m[a]||a.toUpperCase().charCodeAt(0);a in g||(g[a]=[]);g[a].push({shortcut:e[l],scope:b,method:d,key:e[l],mods:c})}}function c(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,function(){d(window.event)})}var f,g={},h={16:!1,18:!1,17:!1,91:!1},l="all",k={"\u21e7":16,shift:16,option:18,"\u2325":18,alt:18,ctrl:17,control:17,command:91,"\u2318":91},m={backspace:8,tab:9,clear:12,enter:13,"return":13,esc:27,escape:27,space:32,left:37,up:38,right:39,down:40,del:46,
"delete":46,home:36,end:35,pageup:33,pagedown:34,",":188,".":190,"/":191,"`":192,"-":189,"=":187,";":186,"'":222,"[":219,"]":221,"\\":220};for(f=1;f<20;f++)k["f"+f]=111+f;for(f in k)d[f]=!1;c(document,"keydown",function(a){var c,j,f,m,p;j=(a.target||a.srcElement).tagName;c=a.keyCode;if(c==93||c==224)c=91;if(c in h)for(f in h[c]=!0,k)k[f]==c&&(d[f]=!0);else if(!(j=="INPUT"||j=="SELECT"||j=="TEXTAREA")&&c in g)for(m=0;m<g[c].length;m++)if(j=g[c][m],j.scope==l||j.scope=="all"){p=j.mods.length>0;for(f in h)if(!h[f]&&
b(j.mods,+f)>-1||h[f]&&b(j.mods,+f)==-1)p=!1;if((j.mods.length==0&&!h[16]&&!h[18]&&!h[17]&&!h[91]||p)&&j.method(a,j)===!1)if(a.preventDefault?a.preventDefault():a.returnValue=!1,a.stopPropagation&&a.stopPropagation(),a.cancelBubble)a.cancelBubble=!0}});c(document,"keyup",function(a){var a=a.keyCode,b;if(a==93||a==224)a=91;if(a in h)for(b in h[a]=!1,k)k[b]==a&&(d[b]=!1)});a.key=d;a.key.setScope=function(a){l=a||"all"};if(typeof module!=="undefined")module.exports=key})(b);b.mouse={x:0,y:0};document.onmousemove=
function(a){var e=0,d=0;if(!a)a=window.event;if(a.pageX||a.pageY)e=a.pageX,d=a.pageY;else if(a.clientX||a.clientY)e=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;b.mouse.x=e;b.mouse.y=d}(function(a){function b(a,d){for(var c=a.length;c--;)if(a[c]===d)return c;return-1}function d(a,b){return"[object "+a+"]"===h.call(b)}var c,f,g,h=Object.prototype.toString;c=function(){function a(){return d.length}var d=
[],c=new signals.Signal,h=new signals.Signal;return{_routes:d,addRoute:function(b,c,e){b=new f(b,c,e);c=a();do--c;while(d[c]&&b._priority<=d[c]._priority);d.splice(c+1,0,b);return b},removeRoute:function(a){var c=b(d,a);c>=0&&d.splice(c,1);a._destroy()},removeAllRoutes:function(){for(var b=a();b--;)d[b]._destroy();d.length=0},parse:function(b){var b=b||"",e;a:{e=b;for(var f=a(),o;o=d[--f];)if(o.match(e)){e=o;break a}e=null}f=e?g.getParamValues(b,e._matchRegexp):null;e?(f?e.matched.dispatch.apply(e.matched,
f):e.matched.dispatch(),h.dispatch(b,e,f)):c.dispatch(b)},bypassed:c,routed:h,getNumRoutes:a,toString:function(){return"[crossroads numRoutes:"+a()+"]"}}}();f=function(a,b,c){this._pattern=a;this._matchRegexp=d("RegExp",a)?a:g.compilePattern(a);this.matched=new signals.Signal;b&&this.matched.add(b);this._priority=c||0};f.prototype={rules:void 0,match:function(a){return this._matchRegexp.test(a)&&(d("RegExp",this._pattern)||this._validateParams(a))},_validateParams:function(a){var b=this.rules,c;for(c in b)if(b.hasOwnProperty(c)&&
!this._isValidParam(a,c))return!1;return!0},_isValidParam:function(a,c){var f=this.rules[c],g=this._getParamValuesObject(a),h=g[c],j;d("RegExp",f)?j=f.test(h):d("Array",f)?j=b(f,h)!==-1:d("Function",f)&&(j=f(h,a,g));return j||!1},_getParamValuesObject:function(a){for(var b=g.getParamIds(this._pattern),a=g.getParamValues(a,this._matchRegexp),c={},d=b.length;d--;)c[b[d]]=a[d];return c},dispose:function(){c.removeRoute(this)},_destroy:function(){this.matched.dispose();this.matched=this._pattern=this._matchRegexp=
null},toString:function(){return'[Route pattern:"'+this._pattern+'", numListeners:'+this.matched.getNumListeners()+"]"}};g=c.patternLexer=function(){var a=/[\\\.\+\*\?\^\$\[\]\(\)\{\}\/\'\#]/g,b=/([^\/]+)/,c=/\{([^\}]+)\}/g,d=RegExp("___CR_PARAM___","g");return{getParamIds:function(a){for(var b=[],d;d=c.exec(a);)b.push(d[1]);return b},getParamValues:function(a,b){var c=b.exec(a);if(c){c.shift();for(var d=c.length,e=[],f;f=c[--d];)e[d]=f===null||f===""||isNaN(f)?f:parseFloat(f);c=e}return c},compilePattern:function(e){e=
e?e.replace(c,"___CR_PARAM___"):"";e=e.replace(a,"\\$&");e=e.replace(d,b.source);return RegExp("^"+e+"$")}}}();a.routes=c}(b));b.json={};b.json.parse=function(a){return(new Function("return "+a))()};b.json.stringify=JSON.stringify||function(a){var b=typeof a;if(b!="object"||a===null)return b=="string"&&(a='"'+a+'"'),String(a);else{var d,c,f=[],g=a&&a.constructor==Array;for(d in a)c=a[d],b=typeof c,b=="string"?c='"'+c+'"':b=="object"&&c!==null&&(c=JSON.stringify(c)),f.push((g?"":'"'+d+'":')+String(c));
return(g?"[":"{")+String(f)+(g?"]":"}")}};b.tmplCache={};b.tmpl=function(a,e){var d=!/\W/.test(a)?b.tmplCache[a]=b.tmplCache[a]||b.tmpl(document.getElementById(a).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+a.replace(/[\r\t\n]/g," ").split("<?").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("?>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');");return e?d(e):
d};b.microtmpl=function(a,b){for(var d in b)a=a.replace(RegExp("{"+d+"}","g"),b[d]);return a};b.pubsub={};b.pubsub.cache={};b.pubsub.publish=function(a,e,d){for(var c=(a=b.pubsub.cache[a])?a.length:0;c--;)a[c].callback.apply(a[c].scope||d||this,e||[])};b.pubsub.subscribe=function(a,e,d){b.pubsub.cache[a]||(b.pubsub.cache[a]=[]);b.pubsub.cache[a].push({callback:e,scope:d||{}});return[a,e,d]};b.pubsub.unsubscribe=function(a){for(var e=b.pubsub.cache[a[0]],a=a[1],d=e?e.length:0;d--;)e[d].callback===
a&&e.splice(d,1)};b.publish=b.pubsub.publish;b.subscribe=b.pubsub.subscribe;b.unsubscribe=b.pubsub.unsubscribe;b.lang={};b.lang.activeLanguage_=n;b.lang.setLang=function(a){b.lang.activeLanguage_=a;return b.lang};b.lang.getLang=function(){return b.lang.activeLanguage_};b.lang.addLang=function(a,e){b.lang[a]={};b.lang.addTranslations(a,e);return b.lang};b.lang.addTranslation=function(a,e,d){b.lang[a][e]=d;return b.lang};b.lang.addTranslations=function(a,e){for(var d=0,c;c=e[d];d++)b.lang.addTranslation(a,
c.source,c.translation);return b.lang};b.lang.translate=function(a,e){var d=b.lang[b.lang.getLang()][a];return!e?d:b.microtmpl(d,e)};b.translate=b.lang.translate;b.setLang=b.lang.setLang;b.getLang=b.lang.getLang;b.addLang=b.lang.addLang;q.holzweg=q.hw=b})(window);if(typeof console!="object"){var fn="log,info,warn,clear,debug,group,groupCollapsed,groupEnd,time,timeEnd,profile,profileEnd".split(",");console={};for(var i=0;i<fn.length;i++)console[fn[i]]=function(){}};
